// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apimodel.proto

// Protobuf Java Version: 4.26.1
package com.example.apis.protos;

public interface APIsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .API apis = 1;</code>
   */
  java.util.List<com.example.apis.protos.API> 
      getApisList();
  /**
   * <code>repeated .API apis = 1;</code>
   */
  com.example.apis.protos.API getApis(int index);
  /**
   * <code>repeated .API apis = 1;</code>
   */
  int getApisCount();
  /**
   * <code>repeated .API apis = 1;</code>
   */
  java.util.List<? extends com.example.apis.protos.APIOrBuilder> 
      getApisOrBuilderList();
  /**
   * <code>repeated .API apis = 1;</code>
   */
  com.example.apis.protos.APIOrBuilder getApisOrBuilder(
      int index);
}
