// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apimodel.proto
// Protobuf Java Version: 4.26.1

package com.example.apis.protos;

public final class APIsProtos {
  private APIsProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      APIsProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_API_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_API_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_APIs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016apimodel.proto\"E\n\003API\022\n\n\002id\030\001 \001(\t\022\014\n\004n" +
      "ame\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\017\n\007versio" +
      "n\030\004 \001(\005\"\032\n\004APIs\022\022\n\004apis\030\001 \003(\0132\004.APIB\'\n\027c" +
      "om.example.apis.protosB\nAPIsProtosP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_API_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_API_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_API_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Version", });
    internal_static_APIs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_APIs_descriptor,
        new java.lang.String[] { "Apis", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
