// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apimodel.proto

// Protobuf Java Version: 4.26.1
package com.example.apis.protos;

/**
 * Protobuf type {@code APIs}
 */
public final class APIs extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:APIs)
    APIsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      APIs.class.getName());
  }
  // Use APIs.newBuilder() to construct.
  private APIs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private APIs() {
    apis_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.apis.protos.APIsProtos.internal_static_APIs_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.apis.protos.APIsProtos.internal_static_APIs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.apis.protos.APIs.class, com.example.apis.protos.APIs.Builder.class);
  }

  public static final int APIS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.apis.protos.API> apis_;
  /**
   * <code>repeated .API apis = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.apis.protos.API> getApisList() {
    return apis_;
  }
  /**
   * <code>repeated .API apis = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.apis.protos.APIOrBuilder>
      getApisOrBuilderList() {
    return apis_;
  }
  /**
   * <code>repeated .API apis = 1;</code>
   */
  @java.lang.Override
  public int getApisCount() {
    return apis_.size();
  }
  /**
   * <code>repeated .API apis = 1;</code>
   */
  @java.lang.Override
  public com.example.apis.protos.API getApis(int index) {
    return apis_.get(index);
  }
  /**
   * <code>repeated .API apis = 1;</code>
   */
  @java.lang.Override
  public com.example.apis.protos.APIOrBuilder getApisOrBuilder(
      int index) {
    return apis_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < apis_.size(); i++) {
      output.writeMessage(1, apis_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < apis_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, apis_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.apis.protos.APIs)) {
      return super.equals(obj);
    }
    com.example.apis.protos.APIs other = (com.example.apis.protos.APIs) obj;

    if (!getApisList()
        .equals(other.getApisList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getApisCount() > 0) {
      hash = (37 * hash) + APIS_FIELD_NUMBER;
      hash = (53 * hash) + getApisList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.apis.protos.APIs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.apis.protos.APIs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.apis.protos.APIs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.apis.protos.APIs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.apis.protos.APIs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.apis.protos.APIs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.apis.protos.APIs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.apis.protos.APIs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.apis.protos.APIs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.apis.protos.APIs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.apis.protos.APIs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.apis.protos.APIs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.apis.protos.APIs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code APIs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:APIs)
      com.example.apis.protos.APIsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.apis.protos.APIsProtos.internal_static_APIs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.apis.protos.APIsProtos.internal_static_APIs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.apis.protos.APIs.class, com.example.apis.protos.APIs.Builder.class);
    }

    // Construct using com.example.apis.protos.APIs.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (apisBuilder_ == null) {
        apis_ = java.util.Collections.emptyList();
      } else {
        apis_ = null;
        apisBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.apis.protos.APIsProtos.internal_static_APIs_descriptor;
    }

    @java.lang.Override
    public com.example.apis.protos.APIs getDefaultInstanceForType() {
      return com.example.apis.protos.APIs.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.apis.protos.APIs build() {
      com.example.apis.protos.APIs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.apis.protos.APIs buildPartial() {
      com.example.apis.protos.APIs result = new com.example.apis.protos.APIs(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.apis.protos.APIs result) {
      if (apisBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          apis_ = java.util.Collections.unmodifiableList(apis_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.apis_ = apis_;
      } else {
        result.apis_ = apisBuilder_.build();
      }
    }

    private void buildPartial0(com.example.apis.protos.APIs result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.apis.protos.APIs) {
        return mergeFrom((com.example.apis.protos.APIs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.apis.protos.APIs other) {
      if (other == com.example.apis.protos.APIs.getDefaultInstance()) return this;
      if (apisBuilder_ == null) {
        if (!other.apis_.isEmpty()) {
          if (apis_.isEmpty()) {
            apis_ = other.apis_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureApisIsMutable();
            apis_.addAll(other.apis_);
          }
          onChanged();
        }
      } else {
        if (!other.apis_.isEmpty()) {
          if (apisBuilder_.isEmpty()) {
            apisBuilder_.dispose();
            apisBuilder_ = null;
            apis_ = other.apis_;
            bitField0_ = (bitField0_ & ~0x00000001);
            apisBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getApisFieldBuilder() : null;
          } else {
            apisBuilder_.addAllMessages(other.apis_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.apis.protos.API m =
                  input.readMessage(
                      com.example.apis.protos.API.parser(),
                      extensionRegistry);
              if (apisBuilder_ == null) {
                ensureApisIsMutable();
                apis_.add(m);
              } else {
                apisBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.apis.protos.API> apis_ =
      java.util.Collections.emptyList();
    private void ensureApisIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        apis_ = new java.util.ArrayList<com.example.apis.protos.API>(apis_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.apis.protos.API, com.example.apis.protos.API.Builder, com.example.apis.protos.APIOrBuilder> apisBuilder_;

    /**
     * <code>repeated .API apis = 1;</code>
     */
    public java.util.List<com.example.apis.protos.API> getApisList() {
      if (apisBuilder_ == null) {
        return java.util.Collections.unmodifiableList(apis_);
      } else {
        return apisBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public int getApisCount() {
      if (apisBuilder_ == null) {
        return apis_.size();
      } else {
        return apisBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public com.example.apis.protos.API getApis(int index) {
      if (apisBuilder_ == null) {
        return apis_.get(index);
      } else {
        return apisBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder setApis(
        int index, com.example.apis.protos.API value) {
      if (apisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApisIsMutable();
        apis_.set(index, value);
        onChanged();
      } else {
        apisBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder setApis(
        int index, com.example.apis.protos.API.Builder builderForValue) {
      if (apisBuilder_ == null) {
        ensureApisIsMutable();
        apis_.set(index, builderForValue.build());
        onChanged();
      } else {
        apisBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder addApis(com.example.apis.protos.API value) {
      if (apisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApisIsMutable();
        apis_.add(value);
        onChanged();
      } else {
        apisBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder addApis(
        int index, com.example.apis.protos.API value) {
      if (apisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApisIsMutable();
        apis_.add(index, value);
        onChanged();
      } else {
        apisBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder addApis(
        com.example.apis.protos.API.Builder builderForValue) {
      if (apisBuilder_ == null) {
        ensureApisIsMutable();
        apis_.add(builderForValue.build());
        onChanged();
      } else {
        apisBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder addApis(
        int index, com.example.apis.protos.API.Builder builderForValue) {
      if (apisBuilder_ == null) {
        ensureApisIsMutable();
        apis_.add(index, builderForValue.build());
        onChanged();
      } else {
        apisBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder addAllApis(
        java.lang.Iterable<? extends com.example.apis.protos.API> values) {
      if (apisBuilder_ == null) {
        ensureApisIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, apis_);
        onChanged();
      } else {
        apisBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder clearApis() {
      if (apisBuilder_ == null) {
        apis_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        apisBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public Builder removeApis(int index) {
      if (apisBuilder_ == null) {
        ensureApisIsMutable();
        apis_.remove(index);
        onChanged();
      } else {
        apisBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public com.example.apis.protos.API.Builder getApisBuilder(
        int index) {
      return getApisFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public com.example.apis.protos.APIOrBuilder getApisOrBuilder(
        int index) {
      if (apisBuilder_ == null) {
        return apis_.get(index);  } else {
        return apisBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public java.util.List<? extends com.example.apis.protos.APIOrBuilder> 
         getApisOrBuilderList() {
      if (apisBuilder_ != null) {
        return apisBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(apis_);
      }
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public com.example.apis.protos.API.Builder addApisBuilder() {
      return getApisFieldBuilder().addBuilder(
          com.example.apis.protos.API.getDefaultInstance());
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public com.example.apis.protos.API.Builder addApisBuilder(
        int index) {
      return getApisFieldBuilder().addBuilder(
          index, com.example.apis.protos.API.getDefaultInstance());
    }
    /**
     * <code>repeated .API apis = 1;</code>
     */
    public java.util.List<com.example.apis.protos.API.Builder> 
         getApisBuilderList() {
      return getApisFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.apis.protos.API, com.example.apis.protos.API.Builder, com.example.apis.protos.APIOrBuilder> 
        getApisFieldBuilder() {
      if (apisBuilder_ == null) {
        apisBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.example.apis.protos.API, com.example.apis.protos.API.Builder, com.example.apis.protos.APIOrBuilder>(
                apis_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        apis_ = null;
      }
      return apisBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:APIs)
  }

  // @@protoc_insertion_point(class_scope:APIs)
  private static final com.example.apis.protos.APIs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.apis.protos.APIs();
  }

  public static com.example.apis.protos.APIs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APIs>
      PARSER = new com.google.protobuf.AbstractParser<APIs>() {
    @java.lang.Override
    public APIs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APIs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APIs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.apis.protos.APIs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

