# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Protobuf
on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Install protobuf
      run: |
        sudo apt install -y protobuf-compiler
        protoc --version
    - name: Compile the proto file
      run: |
        mkdir -p src/main/java/com/example/compile_try
        protoc --java_out="src/main/java/com/example/compile_try" src/main/java/com/example/apimodel.proto
    - name: List contents of the directory
      run: ls -la src/main/java/com/example/
    - name: Displaying java files
      run: cat src/main/java/com/example/compile_try/com/example/apis/protos/*.java
    - name: Run java file
      run: |
        mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt
        java -cp "target/classes:$(cat classpath.txt)" com.example.Main





