# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Protobuf
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm install
        
      - name: Initialize npm package
        run: |
          mkdir -p ts_target
          cd ts_target
          npm init -y
          cd ..
          
      - name: Install protobuf
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          protoc --version
          
      - name: List contents of the directory
        run: ls -la src/main/java/com/example/

      - name: Find proto file and set environment variable
        id: set_proto_name
        run: |
          PROTO_FILE=$(find src/main/java/com/example -name "*.proto" | head -n 1)
          PROTO_NAME=$(basename "$PROTO_FILE" .proto)
          echo "PROTO_NAME=$PROTO_NAME" >> $GITHUB_ENV
          
      - name: Compile the proto file
        run: |
          mkdir -p src/main/java/com/example/compile_try
          mkdir -p src/main/java/com/example/ts_files
          protoc --java_out="src/main/java/com/example/compile_try" src/main/java/com/example/apimodel.proto
          protoc --plugin="protoc-gen-ts=/jome/ydh/node_modules/.bin/protoc-gen-ts" --ts_opt=esModuleInterop=true --experimental_allow_proto3_optional --ts_out="src/main/java/com/example/ts_files" src/main/java/com/example/apimodel.proto
      - name: List generated java fils
        run: ls /home/runner/work/ProtoBuf/ProtoBuf/src/main/java/com/example/compile_try/files
        
      - name: List generated TypeScript fils
        run: ls /home/runner/work/ProtoBuf/ProtoBuf/src/main/java/com/example/ts_files/files
        
      - name: Display generated Java files
        run: cat /home/runner/work/ProtoBuf/ProtoBuf/src/main/java/com/example/compile_try/files/*.java
       
      - name: Display generated Typescript files
        run: cat /home/runner/work/ProtoBuf/ProtoBuf/src/main/java/com/example/ts_files/files/*.ts
        
      - name: Download Protobuf Java ad TypeScript library
        run: |
          wget https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.17.3/protobuf-java-3.17.3.jar -P lib
          npm install google-protobuf@latest
          
      - name: Compile Java files
        run: |
          mkdir -p out
          javac -cp lib/protobuf-java-3.17.3.jar -d out src/main/java/com/example/compile_try/files/*.java
          
      - name: Create JAR file with proto name
        run: |
          mkdir -p target
          jar cvf target/${{ env.PROTO_NAME }}.jar -C out .

      - name: Package TypeScript files as NPM package
        run: |
          cp -r com/webmethods/studio/protobuffs/v1/ts_files ts_target/
          cd ts_target
          npm init -y
          npm install google-protobuf@latest
          npm pack
          
      - name: List contents of the target directory
        run: ls -la target
        
      - name: Upload TypeScript Artifact
        uses: actions/upload-artifact@v2
        with:
          name: protofiles_ts
          path: ts_target/*.tgz

      - name: Publish TypeScript package to npm
        run: |
          cd ts_target
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
